-- To calculate the total revenue generated by all completed payments.
SELECT 
    SUM(payment_value) AS total_revenue
FROM order_payments;

-- To measure the average time taken to deliver orders to customers./
SELECT
    AVG(order_delivered_customer_date - order_purchase_timestamp)
    AS avg_delivery_time
FROM orders
WHERE order_delivered_customer_date IS NOT NULL;

-- To identify how many orders were delivered later than the estimated delivery date.
--                           Top Orders
SELECT
    COUNT(*) AS late_orders
FROM orders
WHERE order_delivered_customer_date > order_estimated_delivery_date;



-- To determine which product categories have the highest sales volume.

--                       Product Categories
SELECT
    p.product_category_name,
    COUNT(i.product_id) AS total_sold
FROM order_items i
JOIN products p ON i.product_id = p.product_id
GROUP BY p.product_category_name
ORDER BY total_sold DESC
LIMIT 10;


-- To identify customers with the highest total spending.
--              Top Customers by    
SELECT
    c.customer_unique_id,
    SUM(p.payment_value) AS total_spent
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
JOIN order_payments p ON o.order_id = p.order_id
GROUP BY c.customer_unique_id
ORDER BY total_spent DESC
LIMIT 10;

